openapi: 3.2.0
info:
  title: OpenAPI definition Currencies and rates API
  version: v0.1
  description: '# Exciting News


    Hey there, amazing developers!'
servers:
- url: https://{environment}.rarible.org
  description: Production (Mainnet)
  variables:
    environment:
      enum:
      - api
      - testnet-api
      default: api
security:
- ApiKeyAuth: []
tags:
- name: Currencies and rates
  x-controller: CurrencyController
paths:
  /v0.1/currencies/{currencyId}/rates/usd:
    get:
      tags:
      - Currencies and rates
      summary: Get USD rate
      description: Get currency USD rate by currency blockchain's address
      operationId: getUsdRate
      parameters:
      - name: currencyId
        in: path
        required: true
        description: Currency Id, has format `ETHEREUM:${token}` or `ETHEREUM:${token}:${tokenId}`
        schema:
          $ref: '#/components/schemas/CurrencyId'
      - name: at
        in: query
        required: true
        description: Date and time for getting currency USD rate (if not specified, returns actual rate)
        example: '2022-01-01T12:00:00Z'
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyUsdRate'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /v0.1/currencies/all:
    get:
      tags:
      - Currencies and rates
      summary: Get supported currencies
      description: List of currencies, supported by Protocol
      operationId: getAllCurrencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currencies'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    BigDecimal:
      type: string
      example: 123456.789
    UnionApiErrorServerError:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          enum:
          - UNKNOWN
          default: UNKNOWN
        message:
          type: string
          description: Error message
    CurrencyUsdRate:
      type: object
      required:
      - symbol
      - rate
      - date
      properties:
        currencyId:
          deprecated: true
          type: string
          description: Currency Id
          example: usdc
        symbol:
          type: string
          description: Currency Symbol
          example: usdc
        abbreviation:
          type: string
        rate:
          $ref: '#/components/schemas/BigDecimal'
        date:
          type: string
          format: date-time
          description: Date and time of currency USD rate
    CurrencyId:
      type: string
      description: Currency Id, has format `ETHEREUM:${token}` or `ETHEREUM:${token}:${tokenId}`
      example: ETHEREUM:0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    Currencies:
      type: object
      required:
      - currencies
      properties:
        currencies:
          type: array
          items:
            $ref: '#/components/schemas/Currency'
    UnionApiErrorBadRequest:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          enum:
          - BAD_REQUEST
          - VALIDATION
          default: BAD_REQUEST
        message:
          type: string
          description: Error message
    Currency:
      type: object
      properties:
        currencyId:
          $ref: '#/components/schemas/CurrencyId'
        symbol:
          type: string
        abbreviation:
          type: string
        alias:
          type: string
          description: Alias to real coin, 'usd' means 1:1 to USD
        rate:
          $ref: '#/components/schemas/BigDecimal'
        decimals:
          type: integer
          format: int32
          description: Number of decimals
      required:
      - currencyId
      - symbol
      - decimals
  responses:
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnionApiErrorServerError'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnionApiErrorBadRequest'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-default: 11111111-1111-1111-1111-111111111111
