openapi: 3.2.0
info:
  title: OpenAPI definition Signature operations API
  version: v0.1
  description: '# Exciting News


    Hey there, amazing developers!'
servers:
- url: https://{environment}.rarible.org
  description: Production (Mainnet)
  variables:
    environment:
      enum:
      - api
      - testnet-api
      default: api
security:
- ApiKeyAuth: []
tags:
- name: Signature operations
  x-controller: SignatureController
paths:
  /v0.1/signature/validate:
    post:
      tags:
      - Signature operations
      summary: Check Order's signature
      description: Checks if Order's signature is valid and returns 'true' if it so, 'false' otherwise
      operationId: validate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureValidationForm'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /v0.1/signature/input:
    post:
      tags:
      - Signature operations
      summary: Generate signed input
      description: Generate input string to sign operation
      operationId: getInput
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureInputForm'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureInput'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    OpenSeaFillOrderSignatureInputForm:
      type: object
      required:
      - orderId
      properties:
        '@type':
          type: string
          enum:
          - OPEN_SEA_ORDER_FILL
        signature:
          description: SeaPort order hash in 'native' format
          example: '0xf3104d38a35c59d2612a6128c9e2bbfabf16f26b2db393801cc20398f10079f2'
          type: string
    SignatureInputForm:
      type: object
      description: Form contains required data to generate input message for signing. All fields should be specified in 'native' manner, i.e. without BLOCKCHAIN prefixes
      required:
      - blockchain
      properties:
        blockchain:
          $ref: '#/components/schemas/Blockchain'
      oneOf:
      - $ref: '#/components/schemas/OpenSeaFillOrderSignatureInputForm'
    Blockchain:
      type: string
      enum:
      - APTOS
      - ETHEREUM
      - POLYGON
      - SOLANA
      - ARBITRUM
      - CHILIZ
      - LIGHTLINK
      - ZKSYNC
      - BASE
      - RARI
      - ZKLINK
      - QUAI
      - ECLIPSE
      - ELECTRONEUM
      - SAAKURU
      - OASIS
      - MATCH
      - MOONBEAM
      - ETHERLINK
      - ZKCANDY
      - BERACHAIN
      - ABSTRACT
      - SHAPE
      - TELOS
      - HEDERAEVM
      - VICTION
      - SETTLUS
      - GOAT
      - HYPEREVM
      - MEGAETH
      - MEGAETHTESTNET
      - MEGAETHTESTNETV2
      - BASECAMP
      - CAMP
      - SOMNIA
      - ARENAZ
      - INJECTIVE
      - INJECTIVETESTNET
      - APECHAIN
      - BLOCKCHAINKEK
      - STELLAR
      - ZILLIQA
      - FRAXTAL
      - XLAYER
      - MONAD
      example: ETHEREUM
    SignatureInput:
      type: object
      required:
      - input
      properties:
        input:
          type: string
    UnionApiErrorServerError:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          enum:
          - UNKNOWN
          default: UNKNOWN
        message:
          type: string
          description: Error message
    UnionAddress:
      type: string
      description: Blockchain address in Union format `${blockchainGroup}:${token}`
      example: ETHEREUM:0x4765273c477c2dc484da4f1984639e943adccfeb
    SignatureValidationForm:
      required:
      - signer
      - message
      - signature
      type: object
      properties:
        signer:
          $ref: '#/components/schemas/UnionAddress'
        publicKey:
          type: string
          description: The creator's public key
        message:
          type: string
        signature:
          type: string
          description: Digital signature of the signer
        algorithm:
          description: Algorithm used for signature generation (don't specify if default algo is used)
          type: string
    UnionApiErrorBadRequest:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          enum:
          - BAD_REQUEST
          - VALIDATION
          default: BAD_REQUEST
        message:
          type: string
          description: Error message
  responses:
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnionApiErrorServerError'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnionApiErrorBadRequest'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-default: 11111111-1111-1111-1111-111111111111
